name: Repository Monitor
on:
  push:
  pull_request:
    types: [opened, closed, reopened]
  create:
  delete:
  issues:
    types: [opened, closed, reopened]
  issue_comment:
    types: [created]
  watch:
    types: [started]
  fork:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Slack
        env:
          GLOBAL_SLACK_WEBHOOK_URL: ${{ secrets.GLOBAL_SLACK_WEBHOOK_URL }}
        run: |
          EVENT_TYPE="${{ github.event_name }}"
          REPO="${{ github.repository }}"
          ACTOR="${{ github.actor }}"

          case $EVENT_TYPE in
            push)
              MESSAGE="🔨 *New Push to Repository*
              • *Repository:* \`$REPO\`
              • *Actor:* \`$ACTOR\`
              • *Branch:* \`${{ github.ref_name }}\`
              • *Commit:* \`${{ github.sha }}\`
              • *Message:* \`${{ github.event.head_commit.message }}\`
              • <${{ github.event.head_commit.url }}|View Commit>"
              ;;
            pull_request)
              PR_ACTION="${{ github.event.action }}"
              PR_TITLE="${{ github.event.pull_request.title }}"
              PR_URL="${{ github.event.pull_request.html_url }}"
              MESSAGE="🔀 *Pull Request $PR_ACTION*
              • *Repository:* \`$REPO\`
              • *Actor:* \`$ACTOR\`
              • *Title:* $PR_TITLE
              • <$PR_URL|View Pull Request>"
              ;;
            create | delete)
              REF_TYPE="${{ github.event.ref_type }}"
              REF="${{ github.event.ref }}"
              MESSAGE="🏷️ *$REF_TYPE $EVENT_TYPE*
              • *Repository:* \`$REPO\`
              • *Actor:* \`$ACTOR\`
              • *$REF_TYPE:* \`$REF\`"
              ;;
            issues)
              ISSUE_ACTION="${{ github.event.action }}"
              ISSUE_TITLE="${{ github.event.issue.title }}"
              ISSUE_URL="${{ github.event.issue.html_url }}"
              MESSAGE="📌 *Issue $ISSUE_ACTION*
              • *Repository:* \`$REPO\`
              • *Actor:* \`$ACTOR\`
              • *Title:* $ISSUE_TITLE
              • <$ISSUE_URL|View Issue>"
              ;;
            issue_comment)
              ISSUE_TITLE="${{ github.event.issue.title }}"
              COMMENT_URL="${{ github.event.comment.html_url }}"
              MESSAGE="💬 *New Comment on Issue*
              • *Repository:* \`$REPO\`
              • *Actor:* \`$ACTOR\`
              • *Issue:* $ISSUE_TITLE
              • <$COMMENT_URL|View Comment>"
              ;;
            watch)
              MESSAGE="⭐ *Repository Starred*
              • *Repository:* \`$REPO\`
              • *Starred by:* \`$ACTOR\`"
              ;;
            fork)
              FORK_URL="${{ github.event.forkee.html_url }}"
              MESSAGE="🍴 *Repository Forked*
              • *Original Repository:* \`$REPO\`
              • *Forked by:* \`$ACTOR\`
              • <$FORK_URL|View Fork>"
              ;;
            release)
              RELEASE_NAME="${{ github.event.release.name }}"
              RELEASE_URL="${{ github.event.release.html_url }}"
              MESSAGE="🚀 *New Release Published*
              • *Repository:* \`$REPO\`
              • *Actor:* \`$ACTOR\`
              • *Release:* $RELEASE_NAME
              • <$RELEASE_URL|View Release>"
              ;;
            *)
              MESSAGE="🔔 *Unhandled Event*
              • *Repository:* \`$REPO\`
              • *Event Type:* \`$EVENT_TYPE\`"
              ;;
          esac

          # Escape special characters for JSON
          MESSAGE=$(echo "$MESSAGE" | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')

          curl -X POST -H "Content-Type: application/json" -d "{
            \"text\": \"$MESSAGE\"
          }" $GLOBAL_SLACK_WEBHOOK_URL
